apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: booking.aliaksei-zhurauliou.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booking
            
            port:
              number: 9002
  - host: admin.aliaksei-zhurauliou.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 9001
  - host: identity.aliaksei-zhurauliou.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 9003