FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /Identity


COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /Identity
COPY --from=build-env /Identity/out .

EXPOSE 9003

ENTRYPOINT ["dotnet", "Identity.Host.dll"]