FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /Booking


COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /Booking
COPY --from=build-env /Booking/out .

EXPOSE 9002

ENTRYPOINT ["dotnet", "Booking.Host.dll"]