apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  TELEGRAM_TOKEN: NjYwMzY4NDg5ODpBQUZYaEZKSzRHd1lLdzh4NDRDNUxzUWNDcTNNQWdMTFVrcw==
  TELEGRAM_CHAT_ID: LTEwMDE4NzY1NTc0ODE=
