apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql